spring:
  profiles:
    active: testing

  datasource:
    platform: h2
    url: jdbc:h2:file:~/users;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE";
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: never
