language: java

addons:
  sonarcloud:
    organization: marcelobojikian
    token:
      secure: SONAR_TOKEN

jdk:
  - openjdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marcelobojikian_Cash-House-Backend-Java

cache:
  directories:
    - '$HOME/.m2/repository' 
