spring:

  port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/cash_house
    platform: postgres
    username: api
    password: password
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        
  flyway:
#    baseline-on-migrate: true

security:
  oauth2:
    client:
      scope: password
      client-id: cueva
      client-secret: noop

logging:
  level:
    org.springframework: INFO
    root: ${TEST:WARN}

server:
  error:
    include-stacktrace: never
    
#spring.main.banner-mode=off
