server:
  port: ${PORT:8080}
  
spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  oauth2:
    client:
      scope: ${OAUTH_SCOPE}
      client-id: ${OAUTH_CLIENT_ID}
      client-secret: ${OAUTH_CLIENT_SECRET}
