spring:
      
  flyway:
    enabled: false

  h2:
    console:
      enable: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

  datasource:
    platform: h2
    url: jdbc:h2:file:~/serverHeroku;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE";
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    initialization-mode: always
    data: classpath:schema.sql,classpath:data.sql
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

security:

  jwt:
    key-store: classpath:server.jks
    key-store-password: cash-house-password
    key-pair-alias: cash-house-oauth-jwt
    key-pair-password: cash-house-pass
